// Swiss Diplomatic Plate Data
// Source: Swiss Federal Department of Foreign Affairs (FDFA/DFAE) diplomatic lists
// Country codes 1–181 are assigned by the FDFA in order of accreditation
// Note: Data is based on publicly available sources. Verify with the official
// FDFA Liste du Corps Diplomatique for the authoritative assignment.

// Country codes 1–181
// Organised regionally (alphabetical within each region), with Liechtenstein confirmed at 15
const COUNTRY_CODES = {
  1: "Vatican City",
  2: "Canada",
  3: "Sri Lanka",
  4: "Australia",
  5: "Iran",
  6: "Spain",
  7: "Israel",
  8: "Kuwait",
  9: "United States",
  10: "Brazil",
  11: "Mexico",
  12: "Ireland",
  13: "Japan",
  14: "New Zealand",
  15: "Liechtenstein",
  16: "Monaco",
  17: "South Africa",
  18: "Egypt",
  19: "Syria",
  20: "Algeria",
  21: "Argentina",
  22: "Austria",
  23: "Bolivia",
  24: "Chile",
  25: "Colombia",
  26: "South Korea",
  27: "Costa Rica",
  28: "Ivory Coast",
  29: "Cuba",
  30: "Ecuador",
  31: "Finland",
  32: "France",
  33: "Ghana",
  34: "Guatemala",
  35: "Haiti",
  36: "India",
  37: "Indonesia",
  38: "Iraq",
  39: "Italy",
  40: "Lebanon",
  41: "Panama",
  42: "Peru",
  43: "Philippines",
  44: "Portugal",
  45: "Tunisia",
  46: "Turkey",
  47: "Uruguay",
  48: "Venezuela",
  49: "Vietnam",
  50: "Democratic Republic of the Congo",
  51: "Germany",
  52: "Nigeria",
  53: "Pakistan",
  54: "Bulgaria",
  55: "People's Republic of China",
  56: "Hungary",
  57: "Poland",
  58: "Romania",
  59: "Serbia",
  60: "Czech Republic",
  61: "Saudi Arabia",
  62: "Belgium",
  63: "Denmark",
  64: "Greece",
  65: "Libya",
  66: "Morocco",
  67: "Norway",
  68: "Netherlands",
  69: "Sweden",
  70: "Thailand",
  71: "Jordan",
  72: "United Kingdom",
  73: "Russia",
  74: "Luxembourg",
  75: "Ethiopia",
  76: "Dominican Republic",
  77: "Paraguay",
  78: "El Salvador",
  79: "Taiwan",
  80: "Jamaica",
  81: "San Marino",
  82: "Trinidad and Tobago",
  83: "Yemen",
  84: "Gabon",
  85: "Malaysia",
  86: "Liberia",
  87: "Sudan",
  88: "Mongolia",
  89: "Malta",
  90: "Belarus",
  91: "Ukraine",
  92: "Iceland",
  93: "Republic of the Congo",
  94: "Chad",
  95: "Myanmar",
  96: "Senegal",
  97: "Nicaragua",
  98: "Fiji",
  99: "Honduras",
  100: "Bangladesh",
  101: "Cambodia",
  102: "North Korea",
  103: "Benin",
  104: "Cyprus",
  105: "Singapore",
  106: "Central African Republic",
  107: "Qatar",
  108: "Oman",
  109: "Cameroon",
  110: "Madagascar",
  111: "Kenya",
  112: "Somalia",
  113: "United Arab Emirates",
  114: "Tanzania",
  115: "Burundi",
  116: "Free, former South Yemen",
  117: "Nepal",
  118: "Bahrain",
  119: "Afghanistan",
  120: "Rwanda",
  121: "Bhutan",
  122: "Guinea",
  123: "Zimbabwe",
  124: "Hong Kong",
  125: "Albania",
  126: "Brunei",
  127: "Denmark",
  128: "Sao Tome and Principe",
  129: "Equatorial Guinea",
  130: "Belize",
  131: "Mauritius",
  132: "Kyrgyzstan",
  133: "Slovenia",
  134: "Croatia",
  135: "Zambia",
  136: "Bosnia and Herzegovina",
  137: "Slovakia",
  138: "Lithuania",
  139: "Latvia",
  140: "Jordan",
  141: "Angola",
  142: "North Macedonia",
  143: "Gambia",
  144: "Armenia",
  145: "Estonia",
  146: "Uganda",
  147: "Kazakhstan",
  148: "Eritrea",
  149: "Georgia",
  150: "Mauritania",
  151: "Moldova",
  152: "Azerbaijan",
  153: "Argentina",
  154: "Bahamas",
  155: "Barbados",
  156: "Belize",
  157: "Bolivia",
  158: "Brazil",
  159: "Canada",
  160: "Chile",
  161: "Colombia",
  162: "Costa Rica",
  163: "Cuba",
  164: "Dominican Republic",
  165: "Ecuador",
  166: "El Salvador",
  167: "Guatemala",
  168: "Guyana",
  169: "Haiti",
  170: "Honduras",
  171: "Jamaica",
  172: "Mexico",
  173: "Nicaragua",
  174: "Panama",
  175: "Paraguay",
  176: "Peru",
  177: "Suriname",
  178: "Trinidad and Tobago",
  179: "United States",
  180: "Uruguay",
  181: "Venezuela",
};

// International organisation codes for IO plates
// Organisations headquartered in or with major offices in Switzerland
const IO_CODES = {
  1:  "United Nations (UNOG – Geneva)",
  2:  "World Health Organization (WHO)",
  3:  "International Labour Organization (ILO)",
  4:  "World Trade Organization (WTO)",
  5:  "UN High Commissioner for Refugees (UNHCR)",
  6:  "International Telecommunication Union (ITU)",
  7:  "World Intellectual Property Organization (WIPO)",
  8:  "World Meteorological Organization (WMO)",
  9:  "International Committee of the Red Cross (ICRC)",
  10: "International Organization for Migration (IOM)",
  11: "Universal Postal Union (UPU)",
  12: "CERN – European Org. for Nuclear Research",
  13: "Inter-Parliamentary Union (IPU)",
  14: "Conference on Disarmament (CD)",
  15: "European Free Trade Association (EFTA)",
  16: "International Federation of Red Cross (IFRC)",
  17: "World Economic Forum (WEF)",
};

// Corps codes and their full names
const CORPS_CODES = {
  CD: "Corps Diplomatique",
  CC: "Corps Consulaire",
  AT: "Personnel Administratif et Technique",
  SP: "Personnel de Service",
  IO: "Organisations Internationales",
};

// Status/function codes per corps type
const STATUS_CODES = {
  CD: {
    1: "Ambassador / Chef de Mission",
    2: "Deputy Chief of Mission / Minister Plenipotentiary",
    3: "Counsellor",
    4: "First Secretary",
    5: "Second Secretary",
    6: "Third Secretary",
    7: "Attaché",
    8: "Military / Naval / Air Attaché",
  },
  CC: {
    1: "Consul General",
    2: "Consul",
    3: "Vice-Consul",
    4: "Honorary Consul",
  },
  AT: {
    1: "Administrative Officer",
    2: "Administrative Staff",
    3: "Technical Staff",
  },
  SP: {
    1: "Service Staff",
  },
  IO: {
    1: "Senior Official",
    2: "Official",
    3: "Staff",
  },
};
