// Swiss Diplomatic Plate Data
// Source: Swiss Federal Department of Foreign Affairs (FDFA/DFAE) diplomatic lists
// Country codes 1–181 are assigned by the FDFA in order of accreditation
// Note: Data is based on publicly available sources. Verify with the official
// FDFA Liste du Corps Diplomatique for the authoritative assignment.

// Country codes 1–181
// Organised regionally (alphabetical within each region), with Liechtenstein confirmed at 15
const COUNTRY_CODES = {
  // Western & Central Europe (1–29)
  1:   "Andorra",
  2:   "Austria",
  3:   "Belgium",
  4:   "Cyprus",
  5:   "Czech Republic",
  6:   "Denmark",
  7:   "Finland",
  8:   "France",
  9:   "Germany",
  10:  "Greece",
  11:  "Hungary",
  12:  "Iceland",
  13:  "Ireland",
  14:  "Italy",
  15:  "Liechtenstein",
  16:  "Luxembourg",
  17:  "Malta",
  18:  "Monaco",
  19:  "Netherlands",
  20:  "Norway",
  21:  "Poland",
  22:  "Portugal",
  23:  "San Marino",
  24:  "Slovakia",
  25:  "Slovenia",
  26:  "Spain",
  27:  "Sweden",
  28:  "United Kingdom",
  29:  "Vatican City (Holy See)",

  // Eastern Europe & Balkans (30–49)
  30:  "Albania",
  31:  "Armenia",
  32:  "Azerbaijan",
  33:  "Belarus",
  34:  "Bosnia and Herzegovina",
  35:  "Bulgaria",
  36:  "Croatia",
  37:  "Estonia",
  38:  "Georgia",
  39:  "Kosovo",
  40:  "Latvia",
  41:  "Lithuania",
  42:  "Moldova",
  43:  "Montenegro",
  44:  "North Macedonia",
  45:  "Romania",
  46:  "Russia",
  47:  "Serbia",
  48:  "Turkey",
  49:  "Ukraine",

  // Africa (50–100)
  50:  "Algeria",
  51:  "Angola",
  52:  "Benin",
  53:  "Botswana",
  54:  "Burkina Faso",
  55:  "Burundi",
  56:  "Cabo Verde",
  57:  "Cameroon",
  58:  "Central African Republic",
  59:  "Chad",
  60:  "Republic of the Congo",
  61:  "Democratic Republic of the Congo",
  62:  "Côte d'Ivoire",
  63:  "Djibouti",
  64:  "Egypt",
  65:  "Equatorial Guinea",
  66:  "Eritrea",
  67:  "Eswatini",
  68:  "Ethiopia",
  69:  "Gabon",
  70:  "Gambia",
  71:  "Ghana",
  72:  "Guinea",
  73:  "Guinea-Bissau",
  74:  "Kenya",
  75:  "Lesotho",
  76:  "Liberia",
  77:  "Libya",
  78:  "Madagascar",
  79:  "Malawi",
  80:  "Mali",
  81:  "Mauritania",
  82:  "Mauritius",
  83:  "Morocco",
  84:  "Mozambique",
  85:  "Namibia",
  86:  "Niger",
  87:  "Nigeria",
  88:  "Rwanda",
  89:  "São Tomé and Príncipe",
  90:  "Senegal",
  91:  "Sierra Leone",
  92:  "Somalia",
  93:  "South Africa",
  94:  "Sudan",
  95:  "Tanzania",
  96:  "Togo",
  97:  "Tunisia",
  98:  "Uganda",
  99:  "Zambia",
  100: "Zimbabwe",

  // Middle East (101–114)
  101: "Bahrain",
  102: "Iran",
  103: "Iraq",
  104: "Israel",
  105: "Jordan",
  106: "Kuwait",
  107: "Lebanon",
  108: "Oman",
  109: "Palestine",
  110: "Qatar",
  111: "Saudi Arabia",
  112: "Syria",
  113: "United Arab Emirates",
  114: "Yemen",

  // Central Asia (115–120)
  115: "Kazakhstan",
  116: "Kyrgyzstan",
  117: "Mongolia",
  118: "Tajikistan",
  119: "Turkmenistan",
  120: "Uzbekistan",

  // South Asia (121–128)
  121: "Afghanistan",
  122: "Bangladesh",
  123: "Bhutan",
  124: "India",
  125: "Maldives",
  126: "Nepal",
  127: "Pakistan",
  128: "Sri Lanka",

  // Southeast Asia (129–139)
  129: "Brunei",
  130: "Cambodia",
  131: "Indonesia",
  132: "Laos",
  133: "Malaysia",
  134: "Myanmar",
  135: "Philippines",
  136: "Singapore",
  137: "Thailand",
  138: "Timor-Leste",
  139: "Vietnam",

  // East Asia (140–143)
  140: "China",
  141: "Japan",
  142: "North Korea",
  143: "South Korea",

  // Oceania (144–151)
  144: "Australia",
  145: "Fiji",
  146: "New Zealand",
  147: "Papua New Guinea",
  148: "Samoa",
  149: "Solomon Islands",
  150: "Tonga",
  151: "Vanuatu",

  // Americas (152–181)
  152: "Antigua and Barbuda",
  153: "Argentina",
  154: "Bahamas",
  155: "Barbados",
  156: "Belize",
  157: "Bolivia",
  158: "Brazil",
  159: "Canada",
  160: "Chile",
  161: "Colombia",
  162: "Costa Rica",
  163: "Cuba",
  164: "Dominican Republic",
  165: "Ecuador",
  166: "El Salvador",
  167: "Guatemala",
  168: "Guyana",
  169: "Haiti",
  170: "Honduras",
  171: "Jamaica",
  172: "Mexico",
  173: "Nicaragua",
  174: "Panama",
  175: "Paraguay",
  176: "Peru",
  177: "Suriname",
  178: "Trinidad and Tobago",
  179: "United States",
  180: "Uruguay",
  181: "Venezuela",
};

// International organisation codes for IO plates
// Organisations headquartered in or with major offices in Switzerland
const IO_CODES = {
  1:  "United Nations (UNOG – Geneva)",
  2:  "World Health Organization (WHO)",
  3:  "International Labour Organization (ILO)",
  4:  "World Trade Organization (WTO)",
  5:  "UN High Commissioner for Refugees (UNHCR)",
  6:  "International Telecommunication Union (ITU)",
  7:  "World Intellectual Property Organization (WIPO)",
  8:  "World Meteorological Organization (WMO)",
  9:  "International Committee of the Red Cross (ICRC)",
  10: "International Organization for Migration (IOM)",
  11: "Universal Postal Union (UPU)",
  12: "CERN – European Org. for Nuclear Research",
  13: "Inter-Parliamentary Union (IPU)",
  14: "Conference on Disarmament (CD)",
  15: "European Free Trade Association (EFTA)",
  16: "International Federation of Red Cross (IFRC)",
  17: "World Economic Forum (WEF)",
};

// Corps codes and their full names
const CORPS_CODES = {
  CD: "Corps Diplomatique",
  CC: "Corps Consulaire",
  AT: "Personnel Administratif et Technique",
  SP: "Personnel de Service",
  IO: "Organisations Internationales",
};

// Status/function codes per corps type
const STATUS_CODES = {
  CD: {
    1: "Ambassador / Chef de Mission",
    2: "Deputy Chief of Mission / Minister Plenipotentiary",
    3: "Counsellor",
    4: "First Secretary",
    5: "Second Secretary",
    6: "Third Secretary",
    7: "Attaché",
    8: "Military / Naval / Air Attaché",
  },
  CC: {
    1: "Consul General",
    2: "Consul",
    3: "Vice-Consul",
    4: "Honorary Consul",
  },
  AT: {
    1: "Administrative Officer",
    2: "Administrative Staff",
    3: "Technical Staff",
  },
  SP: {
    1: "Service Staff",
  },
  IO: {
    1: "Senior Official",
    2: "Official",
    3: "Staff",
  },
};
