// Swiss Diplomatic Plate Data
// Source: Swiss Federal Department of Foreign Affairs (FDFA/DFAE) diplomatic lists
// Country codes 1–181 are assigned by the FDFA in order of accreditation
// Note: Data is based on publicly available sources. Verify with the official
// FDFA Liste du Corps Diplomatique for the authoritative assignment.

// Country codes 1–181 in order of accreditation to Switzerland (FDFA/DFAE)
// 116, 172, 178, 180: currently unassigned ("frei")
// 127, 140: source list shows "Dänemark" / "Jordanien" – verify against current FDFA corps diplomatique
const COUNTRY_CODES = {
  1:   "Vatikanstadt",
  2:   "Kanada",
  3:   "Sri Lanka",
  4:   "Australien",
  5:   "Iran",
  6:   "Spanien",
  7:   "Israel",
  8:   "Kuwait",
  9:   "Vereinigte Staaten",
  10:  "Brasilien",
  11:  "Mexiko",
  12:  "Irland",
  13:  "Japan",
  14:  "Neuseeland",
  15:  "Liechtenstein",
  16:  "Monaco",
  17:  "Südafrika",
  18:  "Ägypten",
  19:  "Syrien",
  20:  "Algerien",
  21:  "Argentinien",
  22:  "Österreich",
  23:  "Bolivien",
  24:  "Chile",
  25:  "Kolumbien",
  26:  "Südkorea",
  27:  "Costa Rica",
  28:  "Elfenbeinküste",
  29:  "Kuba",
  30:  "Ecuador",
  31:  "Finnland",
  32:  "Frankreich",
  33:  "Ghana",
  34:  "Guatemala",
  35:  "Haiti",
  36:  "Indien",
  37:  "Indonesien",
  38:  "Irak",
  39:  "Italien",
  40:  "Libanon",
  41:  "Panama",
  42:  "Peru",
  43:  "Philippinen",
  44:  "Portugal",
  45:  "Tunesien",
  46:  "Türkei",
  47:  "Uruguay",
  48:  "Venezuela",
  49:  "Vietnam",
  50:  "Demokratische Republik Kongo",
  51:  "Deutschland",
  52:  "Nigeria",
  53:  "Pakistan",
  54:  "Bulgarien",
  55:  "Volksrepublik China",
  56:  "Ungarn",
  57:  "Polen",
  58:  "Rumänien",
  59:  "Serbien",
  60:  "Tschechien",
  61:  "Saudi-Arabien",
  62:  "Belgien",
  63:  "Dänemark",
  64:  "Griechenland",
  65:  "Libyen",
  66:  "Marokko",
  67:  "Norwegen",
  68:  "Niederlande",
  69:  "Schweden",
  70:  "Thailand",
  71:  "Jordanien",
  72:  "Vereinigtes Königreich",
  73:  "Russland",
  74:  "Luxemburg",
  75:  "Äthiopien",
  76:  "Dominikanische Republik",
  77:  "Paraguay",
  78:  "El Salvador",
  79:  "Chinesisch Taipeh",
  80:  "Jamaika",
  81:  "San Marino",
  82:  "Trinidad und Tobago",
  83:  "Jemen",
  84:  "Gabun",
  85:  "Malaysia",
  86:  "Liberia",
  87:  "Sudan",
  88:  "Mongolei",
  89:  "Malta",
  90:  "Belarus",
  91:  "Ukraine",
  92:  "Island",
  93:  "Republik Kongo",
  94:  "Tschad",
  95:  "Myanmar",
  96:  "Senegal",
  97:  "Nicaragua",
  98:  "Fidschi",
  99:  "Honduras",
  100: "Bangladesch",
  101: "Kambodscha",
  102: "Nordkorea",
  103: "Benin",
  104: "Zypern",
  105: "Singapur",
  106: "Zentralafrikanische Republik",
  107: "Katar",
  108: "Oman",
  109: "Kamerun",
  110: "Madagaskar",
  111: "Kenia",
  112: "Somalia",
  113: "Vereinigte Arabische Emirate",
  114: "Tansania",
  115: "Burundi",
  116: "frei",
  117: "Nepal",
  118: "Bahrain",
  119: "Afghanistan",
  120: "Ruanda",
  121: "Bhutan",
  122: "Guinea",
  123: "Simbabwe",
  124: "Hongkong",
  125: "Albanien",
  126: "Brunei",
  127: "Dänemark",
  128: "São Tomé und Príncipe",
  129: "Äquatorialguinea",
  130: "Belize",
  131: "Mauritius",
  132: "Kirgisistan",
  133: "Slowenien",
  134: "Kroatien",
  135: "Sambia",
  136: "Bosnien und Herzegowina",
  137: "Slowakei",
  138: "Litauen",
  139: "Lettland",
  140: "Jordanien",
  141: "Angola",
  142: "Nordmazedonien",
  143: "Gambia",
  144: "Armenien",
  145: "Estland",
  146: "Uganda",
  147: "Kasachstan",
  148: "Eritrea",
  149: "Georgien",
  150: "Mauretanien",
  151: "Moldau",
  152: "Aserbaidschan",
  153: "Lesotho",
  154: "Barbados",
  155: "Kap Verde",
  156: "Mosambik",
  157: "Andorra",
  158: "Botswana",
  159: "Mali",
  160: "Usbekistan",
  161: "Burkina Faso",
  162: "Namibia",
  163: "Osttimor",
  164: "St. Kitts und Nevis",
  165: "Eswatini",
  166: "Dschibuti",
  167: "Malediven",
  168: "Montenegro",
  169: "Grenada",
  170: "Niger",
  171: "Tadschikistan",
  172: "frei",
  173: "Kosovo",
  174: "Palästina",
  175: "Togo",
  176: "Komoren",
  177: "Turkmenistan",
  178: "frei",
  179: "Sierra Leone",
  180: "frei",
  181: "Südsudan",
};

// International organisation codes for IO plates
// Organisations headquartered in or with major offices in Switzerland
const IO_CODES = {
  1:  "United Nations (UNOG – Geneva)",
  2:  "World Health Organization (WHO)",
  3:  "International Labour Organization (ILO)",
  4:  "World Trade Organization (WTO)",
  5:  "UN High Commissioner for Refugees (UNHCR)",
  6:  "International Telecommunication Union (ITU)",
  7:  "World Intellectual Property Organization (WIPO)",
  8:  "World Meteorological Organization (WMO)",
  9:  "International Committee of the Red Cross (ICRC)",
  10: "International Organization for Migration (IOM)",
  11: "Universal Postal Union (UPU)",
  12: "CERN – European Org. for Nuclear Research",
  13: "Inter-Parliamentary Union (IPU)",
  14: "Conference on Disarmament (CD)",
  15: "European Free Trade Association (EFTA)",
  16: "International Federation of Red Cross (IFRC)",
  17: "World Economic Forum (WEF)",
};

// Corps codes and their full names
const CORPS_CODES = {
  CD: "Corps Diplomatique",
  CC: "Corps Consulaire",
  AT: "Personnel Administratif et Technique",
  SP: "Personnel de Service",
  IO: "Organisations Internationales",
};

// Status/function codes per corps type
const STATUS_CODES = {
  CD: {
    1: "Ambassador / Chef de Mission",
    2: "Deputy Chief of Mission / Minister Plenipotentiary",
    3: "Counsellor",
    4: "First Secretary",
    5: "Second Secretary",
    6: "Third Secretary",
    7: "Attaché",
    8: "Military / Naval / Air Attaché",
  },
  CC: {
    1: "Consul General",
    2: "Consul",
    3: "Vice-Consul",
    4: "Honorary Consul",
  },
  AT: {
    1: "Administrative Officer",
    2: "Administrative Staff",
    3: "Technical Staff",
  },
  SP: {
    1: "Service Staff",
  },
  IO: {
    1: "Senior Official",
    2: "Official",
    3: "Staff",
  },
};
